name: Publish

on: [workflow_dispatch]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u <github-username> --password-stdin
      - name: Docker build
        run: docker build -t docker.pkg.github.com/<path-to-repo>/<image-name>:latest .
      - name: Docker push
        run: docker push docker.pkg.github.com/<path-to-repo>/<image-name>:latest
